export const SAMPLE_PLAYERS = [

///////
///////
///////
///////
//"Premier League"
///////
///////
///////
///////
///////



///////
///////
//"Arsenal"
///////
///////
  {
    name: "Viktor Gyökeres",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CF"],
    Offensive: 87,
    Dribbling: 74,
    Pass: 57,
    Finishing: 85,
    Jampping: 76,
    Speed: 88,
    Stamina: 85,
    Difensive: 47,
    Press: 57,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Leandro Trossard",
    team: "Arsenal",
    league: "Premier League",
    positions: ["LW", "CF","AMF"],
    Offensive: 80,
    Dribbling: 85,
    Pass: 73,
    Finishing: 77,
    Jampping: 63,
    Speed: 79,
    Stamina: 81,
    Difensive: 51,
    Press: 54,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Bukayo Saka",
    team: "Arsenal",
    league: "Premier League",
    positions: ["RW","LW","LSB"],
    Offensive: 83,
    Dribbling: 86,
    Pass: 76,
    Finishing: 79,
    Jampping: 59,
    Speed: 84,
    Stamina: 88,
    Difensive: 56,
    Press: 60,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Noni Madueke",
    team: "Arsenal",
    league: "Premier League",
    positions: ["RW","LW"],
    Offensive: 74,
    Dribbling: 84,
    Pass: 68,
    Finishing: 66,
    Jampping: 62,
    Speed: 90,
    Stamina: 81,
    Difensive: 57,
    Press: 59,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Ethan Nwaneri",
    team: "Arsenal",
    league: "Premier League",
    positions: ["RW", "AMF"],
    Offensive: 79,
    Dribbling: 84,
    Pass: 75,
    Finishing: 71,
    Jampping: 55,
    Speed: 81,
    Stamina: 82,
    Difensive: 50,
    Press: 55,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Gabriel Martinelli",
    team: "Arsenal",
    league: "Premier League",
    positions: ["LW"],
    Offensive: 81,
    Dribbling: 84,
    Pass: 77,
    Finishing: 74,
    Jampping: 59,
    Speed: 89,
    Stamina: 83,
    Difensive: 54,
    Press: 64,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Kai Havertz",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CF", "AMF"],
    Offensive: 88,
    Dribbling: 79,
    Pass: 71,
    Finishing: 82,
    Jampping: 72,
    Speed: 82,
    Stamina: 82,
    Difensive: 56,
    Press: 59,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Gabriel Jesus",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CF","LW"],
    Offensive: 85,
    Dribbling: 77,
    Pass: 64,
    Finishing: 80,
    Jampping: 72,
    Speed: 80,
    Stamina: 77,
    Difensive: 52,
    Press: 56,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Andre Harriman",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CF","LW"],
    Offensive: 83,
    Dribbling: 72,
    Pass: 57,
    Finishing: 80,
    Jampping: 71,
    Speed: 73,
    Stamina: 77,
    Difensive: 52,
    Press: 53,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Eberechi Eze",
    team: "Arsenal",
    league: "Premier League",
    positions: ["AMF","RW","CMF"],
    Offensive: 78,
    Dribbling: 93,
    Pass: 79,
    Finishing: 73,
    Jampping: 57,
    Speed: 79,
    Stamina: 83,
    Difensive: 58,
    Press: 62,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Martin Ødegaard",
    team: "Arsenal",
    league: "Premier League",
    positions: ["AMF","CMF"],
    Offensive: 81,
    Dribbling: 89,
    Pass: 87,
    Finishing: 72,
    Jampping: 57,
    Speed: 68,
    Stamina: 82,
    Difensive: 65,
    Press: 67,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Declan Rice",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CMF", "DMF"],
    Offensive: 64,
    Dribbling: 83,
    Pass: 87,
    Finishing: 64,
    Jampping: 73,
    Speed: 74,
    Stamina: 92,
    Difensive: 81,
    Press: 84,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Christian Nørgaard",
    team: "Arsenal",
    league: "Premier League",
    positions: ["DMF","CMF"],
    Offensive: 64,
    Dribbling: 73,
    Pass: 82,
    Finishing: 58,
    Jampping: 72,
    Speed: 68,
    Stamina: 84,
    Difensive: 87,
    Press: 89,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Martín Zubimendi",
    team: "Arsenal",
    league: "Premier League",
    positions: ["DMF","CMF"],
    Offensive: 66,
    Dribbling: 78,
    Pass: 86,
    Finishing: 64,
    Jampping: 71,
    Speed: 71,
    Stamina: 87,
    Difensive: 87,
    Press: 84,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Mikel Merino",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CMF","AMF","CF"],
    Offensive: 74,
    Dribbling: 84,
    Pass: 83,
    Finishing: 72,
    Jampping: 74,
    Speed: 72,
    Stamina: 86,
    Difensive: 73,
    Press: 79,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Max Doman",
    team: "Arsenal",
    league: "Premier League",
    positions: ["RW","AMF","CMF"],
    Offensive: 76,
    Dribbling: 84,
    Pass: 78,
    Finishing: 72,
    Jampping: 58,
    Speed: 77,
    Stamina: 78,
    Difensive: 57,
    Press: 57,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Riccardo Calafiori",
    team: "Arsenal",
    league: "Premier League",
    positions: ["LSB","CB","LW"],
    Offensive: 69,
    Dribbling: 78,
    Pass: 78,
    Finishing: 58,
    Jampping: 79,
    Speed: 87,
    Stamina: 87,
    Difensive: 80,
    Press: 84,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Gabriel Magalhães",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 55,
    Dribbling: 62,
    Pass: 69,
    Finishing: 48,
    Jampping: 83,
    Speed: 73,
    Stamina: 79,
    Difensive: 90,
    Press: 91,
    GK: 40,
    GK01: 2,
  },
  {
    name: "William Saliba",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 50,
    Dribbling: 66,
    Pass: 58,
    Finishing: 53,
    Jampping: 81,
    Speed: 82,
    Stamina: 81,
    Difensive: 91,
    Press: 88,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Jurriën Timber",
    team: "Arsenal",
    league: "Premier League",
    positions: ["RSB","LSB","CB"],
    Offensive: 69,
    Dribbling: 78,
    Pass: 74,
    Finishing: 52,
    Jampping: 80,
    Speed: 87,
    Stamina: 92,
    Difensive: 84,
    Press: 84,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Christian Mosquera",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 46,
    Dribbling: 64,
    Pass: 63,
    Finishing: 40,
    Jampping: 85,
    Speed: 76,
    Stamina: 77,
    Difensive: 85,
    Press: 89,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Ben White",
    team: "Arsenal",
    league: "Premier League",
    positions: ["RSB","CB"],
    Offensive: 68,
    Dribbling: 77,
    Pass: 79,
    Finishing: 51,
    Jampping: 77,
    Speed: 86,
    Stamina: 88,
    Difensive: 85,
    Press: 85,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Myles Lewis-Skelly",
    team: "Arsenal",
    league: "Premier League",
    positions: ["LSB","DMF","CMF"],
    Offensive: 70,
    Dribbling: 77,
    Pass: 80,
    Finishing: 56,
    Jampping: 82,
    Speed: 91,
    Stamina: 91,
    Difensive: 76,
    Press: 81,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Piero Hincapié",
    team: "Arsenal",
    league: "Premier League",
    positions: ["CB","LSB"],
    Offensive: 58,
    Dribbling: 59,
    Pass: 64,
    Finishing: 52,
    Jampping: 79,
    Speed: 83,
    Stamina: 77,
    Difensive: 88,
    Press: 94,
    GK: 40,
    GK01: 2,
  },
  {
    name: "David Raya",
    team: "Arsenal",
    league: "Premier League",
    positions: ["GK"],
    Offensive: 40,
    Dribbling: 47,
    Pass: 62,
    Finishing: 40,
    Jampping: 75,
    Speed: 55,
    Stamina: 58,
    Difensive: 50,
    Press: 44,
    GK: 92,
    GK01: 1,
  },
  {
    name: "Kepa Arrizabalaga",
    team: "Arsenal",
    league: "Premier League",
    positions: ["GK"],
    Offensive: 40,
    Dribbling: 43,
    Pass: 56,
    Finishing: 40,
    Jampping: 77,
    Speed: 55,
    Stamina: 53,
    Difensive: 50,
    Press: 45,
    GK: 89,
    GK01: 1,
  },
  {
    name: "Tommy Setford",
    team: "Arsenal",
    league: "Premier League",
    positions: ["GK"],
    Offensive: 40,
    Dribbling: 41,
    Pass: 51,
    Finishing: 40,
    Jampping: 78,
    Speed: 55,
    Stamina: 50,
    Difensive: 49,
    Press: 45,
    GK: 86,
    GK01: 1,
  },




///////
///////
//"Liverpool"
///////
///////
    {
    name: "Alexander Isak",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CF"],
    Offensive: 89,
    Dribbling: 79,
    Pass: 60,
    Finishing: 84,
    Jampping: 78,
    Speed: 81,
    Stamina: 78,
    Difensive: 44,
    Press: 51,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Cody Gakpo",
    team: "Liverpool",
    league: "Premier League",
    positions: ["LW","CF"],
    Offensive: 82,
    Dribbling: 86,
    Pass: 71,
    Finishing: 77,
    Jampping: 67,
    Speed: 83,
    Stamina: 81,
    Difensive: 54,
    Press: 55,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Mohamed Salah",
    team: "Liverpool",
    league: "Premier League",
    positions: ["RW"],
    Offensive: 90,
    Dribbling: 86,
    Pass: 71,
    Finishing: 86,
    Jampping: 56,
    Speed: 87,
    Stamina: 84,
    Difensive: 44,
    Press: 50,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Federico Chiesa",
    team: "Liverpool",
    league: "Premier League",
    positions: ["LW","RW","CF","AMF"],
    Offensive: 77,
    Dribbling: 86,
    Pass: 70,
    Finishing: 68,
    Jampping: 61,
    Speed: 85,
    Stamina: 74,
    Difensive: 58,
    Press: 61,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Hugo Ekitike",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CF"],
    Offensive: 88,
    Dribbling: 77,
    Pass: 60,
    Finishing: 87,
    Jampping: 73,
    Speed: 88,
    Stamina: 78,
    Difensive: 47,
    Press: 48,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Kaide Gordon",
    team: "Liverpool",
    league: "Premier League",
    positions: ["RW","LW","CF"],
    Offensive: 77,
    Dribbling: 81,
    Pass: 61,
    Finishing: 64,
    Jampping: 57,
    Speed: 87,
    Stamina: 77,
    Difensive: 46,
    Press: 49,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Kieran Morrison",
    team: "Liverpool",
    league: "Premier League",
    positions: ["RW","CMF"],
    Offensive: 81,
    Dribbling: 82,
    Pass: 70,
    Finishing: 69,
    Jampping: 54,
    Speed: 76,
    Stamina: 82,
    Difensive: 51,
    Press: 52,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Rio Numoha",
    team: "Liverpool",
    league: "Premier League",
    positions: ["LW"],
    Offensive: 76,
    Dribbling: 81,
    Pass: 65,
    Finishing: 62,
    Jampping: 57,
    Speed: 81,
    Stamina: 78,
    Difensive: 50,
    Press: 51,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Jayden Danns",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CF"],
    Offensive: 82,
    Dribbling: 75,
    Pass: 60,
    Finishing: 79,
    Jampping: 73,
    Speed: 74,
    Stamina: 79,
    Difensive: 51,
    Press: 55,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Florian Wirtz",
    team: "Liverpool",
    league: "Premier League",
    positions: ["AMF","RW"],
    Offensive: 78,
    Dribbling: 95,
    Pass: 83,
    Finishing: 79,
    Jampping: 57,
    Speed: 81,
    Stamina: 78,
    Difensive: 56,
    Press: 53,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Alexis Mac Allister",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CMF","AMF","DMF"],
    Offensive: 71,
    Dribbling: 83,
    Pass: 87,
    Finishing: 71,
    Jampping: 63,
    Speed: 71,
    Stamina: 88,
    Difensive: 75,
    Press: 76,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Dominik Szoboszlai",
    team: "Liverpool",
    league: "Premier League",
    positions: ["AMF","LW","RW","CMF","RSB"],
    Offensive: 79,
    Dribbling: 85,
    Pass: 81,
    Finishing: 73,
    Jampping: 64,
    Speed: 84,
    Stamina: 88,
    Difensive: 62,
    Press: 63,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Curtis Jones",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CMF","LW","AMF"],
    Offensive: 73,
    Dribbling: 86,
    Pass: 83,
    Finishing: 62,
    Jampping: 63,
    Speed: 79,
    Stamina: 85,
    Difensive: 71,
    Press: 78,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Stefan Bajcetic",
    team: "Liverpool",
    league: "Premier League",
    positions: ["DMF","CB","CMF"],
    Offensive: 64,
    Dribbling: 76,
    Pass: 80,
    Finishing: 55,
    Jampping: 71,
    Speed: 76,
    Stamina: 83,
    Difensive: 87,
    Press: 89,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Ryan Gravenberch",
    team: "Liverpool",
    league: "Premier League",
    positions: ["DMF","CMF"],
    Offensive: 64,
    Dribbling: 81,
    Pass: 81,
    Finishing: 56,
    Jampping: 72,
    Speed: 73,
    Stamina: 92,
    Difensive: 85,
    Press: 88,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Wataru Endo",
    team: "Liverpool",
    league: "Premier League",
    positions: ["DMF","CB","CMF"],
    Offensive: 61,
    Dribbling: 76,
    Pass: 78,
    Finishing: 60,
    Jampping: 72,
    Speed: 70,
    Stamina: 88,
    Difensive: 87,
    Press: 89,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Trey Nyoni",
    team: "Liverpool",
    league: "Premier League",
    positions: ["AMF","CMF"],
    Offensive: 74,
    Dribbling: 82,
    Pass: 81,
    Finishing: 69,
    Jampping: 59,
    Speed: 71,
    Stamina: 79,
    Difensive: 55,
    Press: 56,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Tommy Pilling",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CMF","AMF","DMF"],
    Offensive: 62,
    Dribbling: 65,
    Pass: 71,
    Finishing: 60,
    Jampping: 58,
    Speed: 62,
    Stamina: 72,
    Difensive: 61,
    Press: 68,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Andrew Robertson",
    team: "Liverpool",
    league: "Premier League",
    positions: ["LSB","LW"],
    Offensive: 72,
    Dribbling: 74,
    Pass: 78,
    Finishing: 56,
    Jampping: 66,
    Speed: 86,
    Stamina: 92,
    Difensive: 79,
    Press: 86,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Milos Kerkez",
    team: "Liverpool",
    league: "Premier League",
    positions: ["LSB","LW"],
    Offensive: 68,
    Dribbling: 72,
    Pass: 72,
    Finishing: 55,
    Jampping: 69,
    Speed: 93,
    Stamina: 98,
    Difensive: 74,
    Press: 81,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Conor Bradley",
    team: "Liverpool",
    league: "Premier League",
    positions: ["RSB","RW"],
    Offensive: 68,
    Dribbling: 71,
    Pass: 74,
    Finishing: 55,
    Jampping: 71,
    Speed: 92,
    Stamina: 93,
    Difensive: 76,
    Press: 85,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Jeremie Frimpong",
    team: "Liverpool",
    league: "Premier League",
    positions: ["RSB","RW"],
    Offensive: 69,
    Dribbling: 77,
    Pass: 70,
    Finishing: 69,
    Jampping: 75,
    Speed: 99,
    Stamina: 96,
    Difensive: 74,
    Press: 81,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Calvin Ramsay",
    team: "Liverpool",
    league: "Premier League",
    positions: ["RSB"],
    Offensive: 67,
    Dribbling: 71,
    Pass: 73,
    Finishing: 52,
    Jampping: 66,
    Speed: 90,
    Stamina: 92,
    Difensive: 74,
    Press: 78,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Virgil van Dijk",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 47,
    Dribbling: 59,
    Pass: 65,
    Finishing: 47,
    Jampping: 88,
    Speed: 78,
    Stamina: 72,
    Difensive: 90,
    Press: 88,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Ibrahima Konate",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 55,
    Dribbling: 60,
    Pass: 64,
    Finishing: 51,
    Jampping: 85,
    Speed: 76,
    Stamina: 76,
    Difensive: 87,
    Press: 90,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Joe Gomez",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CB","RSB","LSB"],
    Offensive: 58,
    Dribbling: 67,
    Pass: 68,
    Finishing: 49,
    Jampping: 79,
    Speed: 81,
    Stamina: 74,
    Difensive: 87,
    Press: 86,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Rhys Williams",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 53,
    Dribbling: 58,
    Pass: 62,
    Finishing: 49,
    Jampping: 81,
    Speed: 74,
    Stamina: 73,
    Difensive: 82,
    Press: 83,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Giovanni Reynoe",
    team: "Liverpool",
    league: "Premier League",
    positions: ["CB"],
    Offensive: 59,
    Dribbling: 58,
    Pass: 63,
    Finishing: 49,
    Jampping: 75,
    Speed: 70,
    Stamina: 75,
    Difensive: 84,
    Press: 81,
    GK: 40,
    GK01: 2,
  },
  {
    name: "Alisson Becker",
    team: "Liverpool",
    league: "Premier League",
    positions: ["GK"],
    Offensive: 40,
    Dribbling: 54,
    Pass: 60,
    Finishing: 40,
    Jampping: 80,
    Speed: 56,
    Stamina: 58,
    Difensive: 47,
    Press: 49,
    GK: 92,
    GK01: 1,
  },
  {
    name: "George Mamaradashvili",
    team: "Liverpool",
    league: "Premier League",
    positions: ["GK"],
    Offensive: 40,
    Dribbling: 49,
    Pass: 58,
    Finishing: 40,
    Jampping: 74,
    Speed: 48,
    Stamina: 59,
    Difensive: 46,
    Press: 47,
    GK: 93,
    GK01: 0,
  },
  {
    name: "Freddie Woodman",
    team: "Liverpool",
    league: "Premier League",
    positions: ["GK"],
    Offensive: 40,
    Dribbling: 45,
    Pass: 51,
    Finishing: 40,
    Jampping: 86,
    Speed: 55,
    Stamina: 53,
    Difensive: 46,
    Press: 47,
    GK: 86,
    GK01: 1,
  },
  ];